export const cards = [
    "(Child noises in the background)",
    "Hello, hello?",
    "I need to jump in another call",
    "can everyone go on mute",
    "could you please get closer to the mic",
    "load painful echo/ feedback",
    "Next slide,please:",
    "can we take this offline?",
    "is___on the call?",
    "could you share this slides afterwards?",
    "can somebody grant presenter rights?",
    "can you email that to everyone?",
    "sorry, i had problems logging in",
    "(animal noises in the background)",
    "sorry, i didn't found the conference id",
    "i was having connections issues",
    "i'll have to get back to you",
    "who just joined us ?",
    "sorry,something ____ with my calender went wrong",
    "do you see my screen??",
    "hey, lets wait for ____?",
    "are you going to send it in couple of minutes??",
    "sorry, i was on mute!!!!",
    "can you repeat what you said please??",
  
  ];
  